### ISSUE TITLE
writeRefAxis is midly broken

### ISSUE THREAD

**Issue by bbrelje** [mdolab/pygeo#69]
## Description
DVGeometry.writeRefAxes appears to have broken midly due to a change in OrderedDict(). It should be reg tested but currently is not

### Steps to reproduce issue
1. Call writeRefAxes in the normal manner

### Current behavior
Raises the following error:
```
Traceback (most recent call last):
  File "runFFDExample.py", line 50, in <module>
    DVGeo.writeRefAxes('local_refaxes.dat')
  File "/home/ben/packages/pygeo/pygeo/DVGeometry.py", line 2066, in writeRefAxes
    print(self.points.keys()[0])
TypeError: 'odict_keys' object is not subscriptable
```

### Expected behavior
Should not do that

**Comment by bbrelje** [comment]
Just needs to be cast to a list, I'll take care of it in my docs push
